version: "3.10"
services:
  worker:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - OWNER_ID=${OWNER_ID}
      - MUSIC_BOT_NAME=${MUSIC_BOT_NAME}
      - LOG_GROUP_ID=${LOG_GROUP_ID}
      - STRING_SESSION=${STRING_SESSION}
      - MONGO_DB_URI=${MONGO_DB_URI}
